---
abstract: 'Perl extension for Reading Extensible Business Reporting Language documents '
author:
  - 'Mark Gannon <mark@truenorth.nu>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XBRL
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.25
  Class::Accessor: 0.34
  Date::Manip: 6.3
  Exporter: 5.66
  File::Spec: 3.33
  File::Temp: 0.22
  HTML::Table: 2.08
  LWP::UserAgent: 6.04
  XML::LibXML: 1.9
version: 0.02
